version: '3.9'

services:

  project-storm-db:
    environment:
      - POSTGRES_DB=storm
      - POSTGRES_USER=storm
      - POSTGRES_PASSWORD=storm
    build: ./Postgresql
    volumes:
      - ./Postgresql/storm.sql:/docker-entrypoint-initdb.d/storm.sql
    ports:
      - "5432:5432"

  project-storm-backend:
    build: ./Python
    ports:
      - "8000:8000"
    depends_on:
      - project-storm-db

volumes:
  pg-data:
